### ISSUE TITLE
Downtimes connector fails when no downtimes are fetched from gocdb api

### ISSUE THREAD

**Issue by pkoro** [ARGOeu/ARGO#170] opened 2015-09-17 12:37 UTC
If for a given day no downtimes are recorded on gocdb the connector raises an exception and exits. The issue (I think) comes in from [this point in the code][l1] where an assertion is made that there are indeed downtimes in the xml response from gocdb. However, I think that if there are no downtimes in the response 1) a better error handling should be performed and 2) an empty avro file should be left behind on the filesystem for the compute engine to pick up. 

[l1]: https://github.com/ARGOeu/argo-egi-connectors/blob/devel/bin/downtimes-gocdb-connector.py#L70

**Comment by vrdel** [comment] 2015-09-17 20:25
Yes, I forgot to handle the case of no downtimes at all for a given date. This will be fixed in the upcoming pull request.

**Comment by vrdel** [comment] 2015-09-18 18:45
Hmm, can you actually give me a date for which there are no downtimes reported? I can't reproduce it but I've seen in logs on arstats that it generated unhandled exception once. Wrong assertion is handled so I don't believe it's the culprit, it might pretty be something else.

**Closed** 2015-10-10 15:35 UTC
Labels: Bug, Sync Components
